---
kind: pipeline
name: nonprod
type: docker


steps:

- name: Build
  image: node
  commands:
    - npm install
    
- name: Test
  image: node
  commands:
    - npm test
    
- name: code-analysis
  image: aosapps/drone-sonar-plugin:1.0
  volumes:
  - name: coverage-server
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
